[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://hd-notes-backend.up.railway.app/api"